import pandas as pd

df = pd.read_csv("data/processed/chocolate_shipments_cleaned.csv")

df["Shipdate"] = pd.to_datetime(df["Shipdate"])

print(df.head())
print(df.shape)

# Total Revenue, Cost Price, Proit, Margin%
Total_Revenue = df["Amount"].sum()
Total_Cost = df["Cost_price"].sum()
Total_Profit = df["Profit"].sum()
Profit_margin = (Total_Profit/Total_Revenue)*100

print("Total Revenue : ", Total_Revenue)
print("Total Cost Price : ", Total_Cost)
print("Total Profit : ", Total_Profit)
print("Total Margin% : ", Profit_margin)

# Revenue generated by each region
revenue_by_region = df.groupby("Region")["Amount"].sum().sort_values(ascending=False)

print("\nRevenue by Region:")
print(revenue_by_region)

# Profit Generated by each region
profit_by_region = df.groupby("Region")["Profit"].sum().sort_values(ascending=False)

print("\nProfit by Region:")
print(profit_by_region)

# Combined the two datas and calucalted Margin% for regions
region_performance = pd.concat([revenue_by_region,profit_by_region],axis=1)

region_performance.columns = ["Revenue","Profit"]

region_performance["Profit_Margin%"] = (
    region_performance["Profit"]
    / region_performance["Revenue"]
    * 100
)

print("\nRegion Performance : ")
print(region_performance.sort_values("Profit_Margin%",ascending=False))

# Revenue generated by each Product
revenue_by_product = df.groupby("Product")["Amount"].sum().sort_values(ascending=False)

print("\nRevenue by Product:")
print(revenue_by_product)

# Profit Generated by each Product
profit_by_product = df.groupby("Product").agg(
    Profit=("Profit","sum")).sort_values(by="Profit",ascending=False)

print("\nProfit by Product:")
print(profit_by_product)

# Combined the two datas and calucalted Margin% for Products
products_performance = pd.concat([revenue_by_product,profit_by_product],axis=1)

products_performance.columns = ["Revenue","Profit"]

products_performance["Profit_Margin%"] = (
    products_performance["Profit"]
    / products_performance["Revenue"]
    * 100)

print("\nProducts Performance : ")
print(products_performance.sort_values("Profit_Margin%",ascending=False))

# Top 5 products by profit
print("\nTop 5 Products by Profit:")
print(
    products_performance
    .sort_values("Profit", ascending=False)
    .head(5)
)

# 5 under performing products by profit
print("\nBottom 5 Products by Profit:")
print(
    products_performance
    .sort_values("Profit", ascending=True)
    .head(5)
)

# Identifying the loss for 85% Dark Bars
dark_bars_by_region = df[df["Product"]== "85% Dark Bars"].groupby("Region") .agg(
    Revenue=("Amount","sum"),Cost=("Cost_price", "sum"),Profit=("Profit","sum"),
    Boxes=("Boxes", "sum"),Revenue_per_box=("Revenue_per_box", "mean"),Cost_per_box=("Cost_per_box", "mean"))

dark_bars_by_region["Profit_Margin%"] = (
    dark_bars_by_region["Profit"]
    / dark_bars_by_region["Revenue"]
    * 100
)

print("\n85% Dark Bars by Region:")
print(dark_bars_by_region)

# Calculating values of products per unit
product_unit_economics = (
    df.groupby("Product")
      .agg(
          Revenue=("Amount", "sum"),
          Cost=("Cost_price", "sum"),
          Profit=("Profit", "sum"),
          Boxes=("Boxes", "sum"),
          Revenue_per_box=("Revenue_per_box", "mean"),
          Cost_per_box=("Cost_per_box", "mean")
      )
)

product_unit_economics["Profit_Margin%"] = (
    product_unit_economics["Profit"]
    / product_unit_economics["Revenue"]
    * 100
)

product_unit_economics["Profit_per_box"] = (
    product_unit_economics["Profit"]
    / product_unit_economics["Boxes"]
)

print("\nProduct Unit Economics:")
print(product_unit_economics.sort_values("Profit"))

#Creating Year column for time analysis
df["Year"]= df["Shipdate"].dt.year

# Analysing loss making products by timeperiod
loss_making_products = [
    "85% Dark Bars",
    "Baker's Choco Chips",
    "After Nines"
]

loss_products_by_year = df[df["Product"].isin(loss_making_products)].groupby([
    "Year","Product"])["Profit"].sum()

print("\nLoss-Making Products by Year:")
print(loss_products_by_year)

# Calculating Performance of teams
team_performance = (
    df.groupby("Team")
      .agg(Revenue=("Amount", "sum"),Profit=("Profit", "sum"),Boxes=("Boxes", "sum")))

team_performance["Profit_Margin%"] = (team_performance["Profit"]
    / team_performance["Revenue"]* 100)

print("\nTeam Performance:")
print(team_performance.sort_values("Profit", ascending=False))

# Calculating Sales Person Performance
salesperson_performance = (
    df.groupby("Sales_Person")
      .agg(Revenue=("Amount", "sum"),Profit=("Profit", "sum"),Boxes=("Boxes", "sum")))

salesperson_performance["Profit_Margin%"] = (salesperson_performance["Profit"]
    / salesperson_performance["Revenue"]* 100)

salesperson_performance["Profit_Rank"] = (salesperson_performance["Profit"]
    .rank(method="dense", ascending=False).astype(int))

salesperson_performance["Margin_Rank"] = (salesperson_performance["Profit_Margin%"]
    .rank(method="dense", ascending=False).astype(int))

print("\nSalesperson Performance by Profit:")
print(salesperson_performance.sort_values("Profit_Rank"))

print("\nSalesperson Performance by Margin:")
print(salesperson_performance.sort_values("Margin_Rank"))

# Overall Cancellation Analysis
cancellation_summary = (df.groupby("cancelled").size())

total_shipments = len(df)
cancelled_shipments = df["cancelled"].sum()

cancellation_rate = (cancelled_shipments / total_shipments * 100)

print("\nCancellation Summary:")
print("Total Shipments:", total_shipments)
print("Cancelled Shipments:", cancelled_shipments)
print("Cancellation Rate:", cancellation_rate)

#Cancellation by region
cancellation_by_region = df.groupby("Region").agg(
    Total_Shipments = ("SPID","count"),
    Cancelled_shipments = ("cancelled","sum")
)

cancellation_by_region["Cancellation_Rate%"] = (
    cancellation_by_region["Cancelled_shipments"]
    / cancellation_by_region["Total_Shipments"]
    * 100
)

print("\nCancellation by Region:")
print(cancellation_by_region.sort_values("Cancellation_Rate%", ascending=False))

# Cancellation by Product
cancellation_by_product = df.groupby("Product").agg(
          Total_Shipments=("ShipmentID", "count"),
          Cancelled_Shipments=("cancelled", "sum")
      )

cancellation_by_product["Cancellation_Rate%"] = (
    (cancellation_by_product["Cancelled_Shipments"]
    / cancellation_by_product["Total_Shipments"])* 100
)

print("\nCancellation by Product:")
print(cancellation_by_product.sort_values("Cancellation_Rate%", ascending=False))

# Yearly Performance
yearly_performance = df.groupby("Year").agg(
          Revenue=("Amount", "sum"),Profit=("Profit", "sum"),Boxes=("Boxes", "sum")
      )

yearly_performance["Profit_Margin%"] = (yearly_performance["Profit"]/ yearly_performance["Revenue"] * 100)

print("\nYearly Performance:")
print(yearly_performance)

# Monthly Performance
df["Month"] = df["Shipdate"].dt.to_period("M")

monthly_performance = (
    df.groupby("Month")
      .agg(
          Revenue=("Amount", "sum"),
          Profit=("Profit", "sum"),
          Boxes=("Boxes", "sum")
      )
)

monthly_performance["Profit_Margin%"] = (
    monthly_performance["Profit"]
    / monthly_performance["Revenue"]
    * 100
)

print("\nMonthly Performance:")
print(monthly_performance)



# ==============================
# VISUALIZATION
# ==============================

import matplotlib.pyplot as plt

# Revenue by Region

# Convert revenue to millions
revenue_millions = revenue_by_region / 1_000_000

plt.figure(figsize=(8, 5))

plt.bar(
    revenue_millions.index,
    revenue_millions.values
)

plt.title("Revenue by Region")
plt.xlabel("Region")
plt.ylabel("Revenue (Millions)")

plt.tight_layout()

plt.savefig("charts/revenue_by_region.png")

plt.show()

# Monthly Revenue Trend

monthly_revenue = (
    df.groupby("Month")["Amount"]
      .sum()
)

# Convert to millions
monthly_revenue_millions = monthly_revenue / 1_000_000

plt.figure(figsize=(12, 5))

plt.plot(
    monthly_revenue_millions.index.astype(str),
    monthly_revenue_millions.values,
    marker="o"
)

plt.title("Monthly Revenue Trend")
plt.xlabel("Month")
plt.ylabel("Revenue (Millions)")

plt.xticks(rotation=45)

plt.tight_layout()

plt.savefig("charts/monthly_revenue_trend.png")

plt.show()


# Profit by Product
profit_by_product = profit_by_product["Profit"].sort_values()
# Convert to millions
profit_by_product_millions = profit_by_product / 1_000_000

plt.figure(figsize=(10, 8))

plt.barh(
    profit_by_product_millions.index,
    profit_by_product_millions.values
)

plt.title("Profit by Product")
plt.xlabel("Profit (Millions)")
plt.ylabel("Product")

plt.tight_layout()

plt.savefig("charts/profit_by_product.png")

plt.show()

# Profit Margin by Product

profit_margin_by_product = (
    df.groupby("Product")
      .agg(
          Revenue=("Amount", "sum"),
          Profit=("Profit", "sum")
      )
)

profit_margin_by_product["Profit_Margin%"] = (
    profit_margin_by_product["Profit"]
    / profit_margin_by_product["Revenue"]
    * 100
)

profit_margin_by_product = (
    profit_margin_by_product["Profit_Margin%"]
    .sort_values()
)

plt.figure(figsize=(10, 8))

plt.barh(
    profit_margin_by_product.index,
    profit_margin_by_product.values
)

plt.title("Profit Margin by Product")
plt.xlabel("Profit Margin (%)")
plt.ylabel("Product")

plt.tight_layout()

plt.savefig("charts/profit_margin_by_product.png")

plt.show()